use ProyectoTrip;

CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
lastname varchar(50),
address text not null,
gender varchar(10) not null,
email VARCHAR(90) NOT NULL UNIQUE,
password VARCHAR(90) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
profile_image VARCHAR(255),
bio varchar(255)
);

CREATE TABLE recommendations (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
title VARCHAR(100) NOT NULL,
category VARCHAR(50) NOT NULL,
location VARCHAR(100) NOT NULL,
summary VARCHAR(100) NOT NULL,
details TEXT NOT NULL,
image VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE votes (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
recommendation_id INT NOT NULL,
value INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (recommendation_id) REFERENCES recommendations(id) ON DELETE CASCADE
);


CREATE TABLE comments (
id INT PRIMARY KEY AUTO_INCREMENT,
user_id INT NOT NULL,
recommendation_id INT NOT NULL,
comment TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (recommendation_id) REFERENCES recommendations(id) ON DELETE CASCADE
);
